title: Roslynn Ricard
author: roslynn-ricard
email: roslynnricard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my corner of the internet, I'm glad you're here! This page is still very much under construction
  but it will eventually contain my resume and various other content that i'm 
  sufficiently proud of to share publicly =]. 

  I'd encourage you to check back in a week or two!

# social links
twitter_username: RoslynnRicard # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
